[phases.build]
cmds = [
    "cd SalesDashboard.Api",
    "dotnet restore",
    "dotnet publish -c Release -o /app"
]

[phases.start]
cmd = "cd /app && dotnet SalesDashboard.Api.dll"

[variables]
NIXPACKS_METADATA = "dotnet"