services:
  - type: web
    name: sales-dashboard-api
    runtime: docker
    rootDir: ./SalesDashboard.Api
    dockerfilePath: ./Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: REACT_APP_API_URL
        value: https://sales-dashboard-api-w6vp.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: sales-dashboard-db
          property: connectionString

  - type: web
    name: sales-dashboard-ui
    runtime: static
    rootDir: ./sales-dashboard-ui
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_URL
        value: https://sales-dashboard-api.onrender.com

databases:
  - name: sales-dashboard-db
    databaseName: salesdb
    user: salesuser
